# Here changes of docker-compose for development
version: '3.4'

services:
  ui:
    build:
      context: ./app
      target: development
    volumes:
      - ./build-watch:/opt/app/dist
      - ./app/sources/src:/opt/app/src
      - ./app/sources/public:/opt/app/public
    ports:
      - "3005:3000"
    environment:
      - NODE_ENV=development
      # Allows you to use any host like lvh.me and others
      - DANGEROUSLY_DISABLE_HOST_CHECK=true
      # Enables live reload inside VM or Docker
      - CHOKIDAR_USEPOLLING=true